[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "~5.6.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "~21.0.0"

[[constraint]]
  name = "github.com/blang/semver"
  version = "~3.5.0"
